permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Ç¦oneWick"
  description: |
    Online shop for authentic home decor pieces.
  font_url: "https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700|Playfair+Display:400,700&display=swap"
  colors:
    sidebar: "--color-primary-dark"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-secondary-light"
      buttons.basic: "--color-primary-light"
      buttons.ghost: "--color-primary-dark"
      buttons.blue: "--color-primary-dark"
  rationales:
    typefaces.primary: |
      Montserrat was selected because it is beautiful open font that creates space and calmness. The versatile typeface is to be used for all body copy in most cases and some smaller headings, buttons and cards.
    typefaces.secondary: |
      Playfair Display was selected due to its timelessness and contrast. It is to be used for most headings in banners and product pages.
    colors.primary: |
      The primary colours consist of cool tones of water and wind. They should be used for headings, text, buttons and highlights. The light colours should be used for most backgrounds.
    colors.secondary: |
      The secondary colours contrast the primary palette with warm tones of fire and wood. The rust colour should be used in relation to viewing and adding products to the cart. The light colours can be used for most backgrounds and some text.
